### PR TITLE
Lower default step if value is between 0 and 1

### PR DESCRIPTION
**Pull request by marcofugaro**
This is a thing that I left behind in #5, basically if you would just put `State.Slider(0.3)` (or `0.3`), the step would still go from 0 to 1, and nothing in the middle.

This addresses that bug by setting the step to `0.01` in that case

### CODE REVIEW

**Comment by rreusser** [comment]
Sorry I've been so slow on these PRs. I was messing around a bit with this to see if I could get some reasonably simple function for a nice sort of default: https://observablehq.com/d/c25a9974e1185742

I'm not totally sure where I'm going with that though. In general though, I fully support this 👍

**Comment by rreusser** [comment]
I think my feedback here is just two things:

1. I'd love to figure out how to set a "nice" range no matter what (the 1-2-5 strategy?), but glad to merge without and address that later
2. I think it's best if PRs exclude the build process. If you have multiple PRs pending, they'll conflict hopelessly without a rebuild. Probably easiest to skip in PRs and then make a release commit that builds and bumps the version.

If you want to merge this, then we can release both and do a major version bump (since changing the UMD name is a breaking change.)

**Review by rreusser — APPROVED** [review]

**Comment by marcofugaro** [comment]
1. I can't do that, only you can, you're the man 😄 I love the smart range idea you proposed, but don't know exactly how to implement it. So let's publish this for now and update it when you will have implemented it. 👍 
2. Oops, won't do that again

Alright, let's publish a major, you handle it or should I help you?

**Comment by rreusser** [comment]
You're absolutely welcome to go ahead. I think the new UMD name means a simple major version bump for both. I think the steps are:

1. rebuild if needed
2. bump major version number
3. push
4. add tag, i.e. `git tag -v 2.0.0`
5. push tags, `git push --tags`
6. `npm publish`

Let me know if anything is not clear, but I think you're currently using this more than I am so that I'd love to get you fully on board. I really appreciate it!

**Comment by marcofugaro** [comment]
> I think you're currently using this more than I am

😄

**Comment by marcofugaro** [comment]
@rreusser can you give me permissions on npm? I'm `marcofugaro` https://www.npmjs.com/~marcofugaro

**Comment by marcofugaro** [comment]
@rreusser could you publish the next version? It just needs a `npm publish`

**Pull request merged**
